# hooyad
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooyad-public-demo
  labels:
    app: hooyad-public-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hooyad-public-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hooyad-public-demo
    spec:
      containers:
        - image: ghcr.io/hooya-network/hooyad:v0.1.2
          name: hooyad-public-demo
          # imagePullPolicy: Always
          command: ["/hooyad", "--endpoint=0.0.0.0:8531", "--filestore=/mnt", "--db-uri=sqlite:///mnt/hooya.sqlite"]
          resources:
            requests:
              memory: "2Gi"
          volumeMounts:
            - mountPath: /mnt
              name: hooyad-public-demo-mnt
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: hooyad-public-demo-mnt
          persistentVolumeClaim:
            claimName: hooyad-public-demo-mnt
---
apiVersion: v1
kind: Service
metadata:
  name: hooyad-public-demo
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.40.133
spec:
  selector:
    app: hooyad-public-demo
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
  - name: http
    port: 8531
    targetPort: 8531
    protocol: TCP
---
# hooya-web-proxy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooya-web-proxy-public-demo
  labels:
    app: hooya-web-proxy-public-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hooya-web-proxy-public-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hooya-web-proxy-public-demo
    spec:
      containers:
        - image: ghcr.io/hooya-network/hooya-web-proxy:v0.1.2
          name: hooya-web-proxy-public-demo
          # command: ["/hooya-web-proxy", "--endpoint=10.0.40.133:8531"]
          command: ["/hooya-web-proxy", "--endpoint=10.0.40.133:8531", "--proxy-endpoint=0.0.0.0:8532", "--cors-origins=https://public-demo.hooya.wesl.ee", "--data-dir=/mnt"]
          # command: ["/hooya-web-proxy", "--endpoint=10.0.40.133:8531", "--proxy-endpoint=0.0.0.0:8532", "--data-dir=/mnt"]
          resources:
            requests:
              memory: "128Mi"
          volumeMounts:
            - mountPath: /mnt
              name: hooyad-public-demo-mnt
              readOnly: false
      volumes:
        - name: hooyad-public-demo-mnt
          persistentVolumeClaim:
            claimName: hooyad-public-demo-mnt
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hooya-web-proxy-public-demo
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.40.134
spec:
  selector:
    app: hooya-web-proxy-public-demo
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
  - name: http
    port: 80
    targetPort: 8532
    protocol: TCP
---
# hooya-web-ui
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooya-web-ui-public-demo
  labels:
    app: hooya-web-ui-public-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hooya-web-ui-public-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hooya-web-ui-public-demo
    spec:
      containers:
        - image: ghcr.io/hooya-network/hooya-web-ui:v0.1.2
        # imagePullPolicy: Always
          name: hooya-web-ui-public-demo
          env:
          - name: HOOYA_WEB_PROXY_URL
            value: https://web.public-demo.hooya.wesl.ee
          - name: HOOYA_WEB_PROXY_ENDPOINT
            value: http://10.0.40.134
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hooya-web-ui-public-demo
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.40.135
spec:
  selector:
    app: hooya-web-ui-public-demo
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hooyad-public-demo-nodeport
spec:
  selector:
    app: hooyad-public-demo
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: tcp-hooyad-public-demo
      port: 8630
      targetPort: 8630
      protocol: TCP
      nodePort: 30630
    - name: udp-hooyad-public-demo
      port: 8630
      targetPort: 8630
      protocol: UDP
      nodePort: 30630
