apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooyad
  labels:
    app: hooyad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hooyad
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hooyad
    spec:
      containers:
        - image: ghcr.io/hooya-network/hooyad:v0.1.6
          imagePullPolicy: Always
          name: hooyad
          # command: ["/hooyad", "--endpoint=0.0.0.0:8531", "--filestore=/mnt", "--db-uri=sqlite:///mnt/hooya.sqlite"]
          command: ["/hooyad", "--endpoint=0.0.0.0:8531", "--filestore=/mnt"]
          resources:
            requests:
              memory: "2Gi"
          volumeMounts:
            - mountPath: /mnt
              name: hooyad-mnt
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: hooyad-mnt
          persistentVolumeClaim:
            claimName: hooyad-mnt
---
apiVersion: v1
kind: Service
metadata:
  name: hooyad
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.40.129
spec:
  selector:
    app: hooyad
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
  - name: http
    port: 8531
    targetPort: 8531
    protocol: TCP
---
# hooya-web-proxy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooya-web-proxy
  labels:
    app: hooya-web-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hooya-web-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hooya-web-proxy
    spec:
      containers:
        - image: ghcr.io/hooya-network/hooya-web-proxy:v0.1.5
          imagePullPolicy: Always
          name: hooya-web-proxy
          # command: ["/hooya-web-proxy", "--endpoint=10.0.40.129:8531", "--proxy-endpoint=0.0.0.0:8532", "--cors-origins=http://10.0.40.136", "--data-dir=/mnt"]
          command: ["/hooya-web-proxy", "--endpoint=10.0.40.129:8531", "--proxy-endpoint=0.0.0.0:8532", "--cors-origins=https://hooya.wesl.ee", "--data-dir=/mnt"]
          resources:
            requests:
              memory: "128Mi"
          volumeMounts:
            - mountPath: /mnt
              name: hooyad-mnt
              readOnly: false
      volumes:
        - name: hooyad-mnt
          persistentVolumeClaim:
            claimName: hooyad-mnt
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hooya-web-proxy
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.40.128
spec:
  selector:
    app: hooya-web-proxy
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
  - name: http
    port: 80
    targetPort: 8532
    protocol: TCP
---
# hooya-web-ui
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooya-web-ui
  labels:
    app: hooya-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hooya-web-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hooya-web-ui
    spec:
      containers:
        - image: ghcr.io/hooya-network/hooya-web-ui:v0.1.5
          imagePullPolicy: Always
          name: hooya-web-ui
          env:
          - name: HOOYA_WEB_PROXY_URL
            value: https://web.hooya.wesl.ee
          - name: HOOYA_WEB_PROXY_ENDPOINT
            value: http://10.0.40.136
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hooya-web-ui
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.40.136
spec:
  selector:
    app: hooya-web-ui
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hooyad-nodeport
spec:
  selector:
    app: hooyad
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: tcp-hooyad
      port: 8530
      targetPort: 8530
      protocol: TCP
      nodePort: 30530
    - name: udp-hooyad
      port: 8530
      targetPort: 8530
      protocol: UDP
      nodePort: 30530
