apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooya-web-proxy
  labels:
    app: hooya-web-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hooya-web-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hooya-web-proxy
    spec:
      containers:
        - image: ghcr.io/hooya-network/hooya-web-proxy:v0.1.0-prealpha.2
          name: hooya-web-proxy
          command: ["/hooya-web-proxy", "--endpoint=10.0.10.129:8531"]
          resources:
            requests:
              memory: "128Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hooya-web-proxy
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.10.128
spec:
  selector:
    app: hooya-web-proxy
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
  - name: http
    port: 80
    targetPort: 8532
    protocol: TCP
