apiVersion: apps/v1
kind: Deployment
metadata:
  name: raamen-demo
  labels:
    app: raamen-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raamen-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: raamen-demo
    spec:
      containers:
        - image: ghcr.io/wesl-ee/raamen:v1.0
          name: raamen-demo
          resources:
            requests:
              memory: "128Mi"
          volumeMounts:
            - mountPath: /mnt
              name: raamen-demo-mnt
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: raamen-demo-mnt
          persistentVolumeClaim:
            claimName: raamen-demo-mnt
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: raamen-demo
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.10.130
spec:
  selector:
    app: raamen-demo
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
