apiVersion: v1
kind: PersistentVolume
metadata:
  name: pigallery2-images
  labels:
    type: local
spec:
  storageClassName: pigallery2-images
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "/public/DCIM Gallery"
    server: 10.0.10.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pigallery2-images
spec:
  storageClassName: pigallery2-images
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 30Gi
